# Generated by Django 4.0.1 on 2022-11-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_author', models.CharField(max_length=20)),
                ('post_title', models.CharField(max_length=32)),
                ('post_text', models.CharField(max_length=200)),
                ('post_save', models.BooleanField(default=False)),
            ],
        ),
    ]
