# Generated by Django 4.0.1 on 2022-12-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_comments', models.CharField(max_length=1000)),
                ('post_title', models.CharField(max_length=32)),
                ('post_id', models.IntegerField()),
                ('post_comment_author', models.CharField(max_length=50)),
                ('comment_approve', models.BooleanField(default=False)),
            ],
        ),
    ]
