# Generated by Django 4.0.1 on 2023-01-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_alter_comment_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpost',
            name='post_time',
            field=models.DateTimeField(max_length=200, null=True),
        ),
    ]
