# Generated by Django 4.0.1 on 2023-01-03 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_newpost_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime.now, max_length=200, null=True),
        ),
    ]
