# Generated by Django 4.0.1 on 2023-01-03 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_alter_newpost_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='post_time',
            field=models.DateField(default=datetime.date.today, max_length=200, null=True),
        ),
    ]
