# Generated by Django 4.0.1 on 2023-01-03 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_alter_newpost_post_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newpost',
            name='post_time',
        ),
    ]
