# Generated by Django 4.0.1 on 2023-01-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_newpost_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='post_time',
            field=models.DateField(default='Tue Jan 23', max_length=200, null=True),
        ),
    ]
