# Generated by Django 4.0.1 on 2023-01-04 06:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0012_newpost_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='post_time',
            field=models.DateField(default=django.utils.timezone.now, max_length=200, null=True),
        ),
    ]
