# Generated by Django 4.0.1 on 2023-01-22 08:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0013_alter_newpost_post_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_time',
            field=models.DateField(default=django.utils.timezone.now, max_length=200, null=True),
        ),
    ]
